Fix idea plugin
Summary:
Today I checked GitHub and noticed that the gradle builds are still broken.
This was due to recent changes that I had made, where I renamend the default style.
Looks like I missed updating in this one place here.

Error that is shown from running `ktfmt/smoke_tests.sh`
```
> Task :compileJava FAILED
/Users/nbondanca/fbsource/xplat/ktfmt/ktfmt_idea_plugin/src/main/java/com/facebook/ktfmt/intellij/KtfmtSettings.java:81: error: cannot find symbol
    public UiFormatterStyle uiFormatterStyle = UiFormatterStyle.DEFAULT;
                                                               ^
  symbol:   variable DEFAULT
  location: class UiFormatterStyle
Note: /Users/nbondanca/fbsource/xplat/ktfmt/ktfmt_idea_plugin/src/main/java/com/facebook/ktfmt/intellij/InitialConfigurationStartupActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.
```

Reviewed By: strulovich

Differential Revision: D58463661

fbshipit-source-id: 5b97f475d58b5f7ec3c09facc79aa2770e2b8a8e