Fix main class in pom file. (#264)
Summary:
Building with `mvn install` currently results in a jar with a missing main class, as `main` was moved to core/src/main/java/com/facebook/ktfmt/cli/Main.kt

Pull Request resolved: https://github.com/facebookincubator/ktfmt/pull/264

Test Plan:
Imported from GitHub, without a `Test Plan:` line.

Before this change, trying to run the built jar fails:
```
% $JAVA_HOME/bin/java -jar ~/.m2/repository/com/facebook/ktfmt/0.31-SNAPSHOT/ktfmt-0.31-SNAPSHOT-jar-with-dependencies.jar
Error: Could not find or load main class com.facebook.ktfmt.MainKt
```

After this fix, the JAR loads fine:
```
% $JAVA_HOME/bin/java -jar ~/.m2/repository/com/facebook/ktfmt/0.31-SNAPSHOT/ktfmt-0.31-SNAPSHOT-jar-with-dependencies.jar
Usage: ktfmt [--dropbox-style | --google-style | --kotlinlang-style] File1.kt File2.kt ...
```

Updated the [wiki](https://www.internalfb.com/intern/wiki/Ktfmt_(aka_facebook-kotlin-format)/Testing_Changes/) to include this check.

Reviewed By: hick209

Differential Revision: D33240462

Pulled By: davidtorosyan

fbshipit-source-id: cb5687e8e33e8b00709a2a79c17af27e51cd61bb