Fix build failure due to file format mismatch
Summary:
Make sure to use same version of Google Java Format that we use to format our code.
This will avoid the isses we can [see here](https://github.com/facebook/ktfmt/actions/runs/8529628883/job/23365788968#step:5:515) and below
```
FAILURE: Build failed with an exception.

...

* What went wrong:
Execution failed for task ':spotlessJavaCheck'.
> The following files had format violations:
      src/main/java/com/facebook/ktfmt/intellij/KtfmtConfigurable.java
          @@ -200,9 +200,7 @@
           ············false));
           ··}

          -··/**
          -···*·noinspection·ALL
          -···*/
          +··/**·noinspection·ALL·*/
           ··public·JComponent·$$$getRootComponent$$$()·{
           ····return·panel;
           ··}
  Run './gradlew :spotlessApply' to fix these violations.

...

BUILD FAILED in 2m 6s
Error: Process completed with exit code 1.
```

Reviewed By: cortinico

Differential Revision: D55698986

fbshipit-source-id: 9b6a0a9ba1acbd64baf79f1d66ff17d948dfb657