Fix crash when optional semicolon is used in a long single-line lambda
Summary:
Whenever a lambda:
1. Has a single statement
2. Can't be collapsed due to length
3. Uses an optional semicolon

It fails with:
```
com.google.googlejavaformat.FormattingError: 16:5: error: expected token: ';'; generated } instead
```

This fixes that by slightly reworking how statements are visited.

Reviewed By: hick209

Differential Revision: D32708821

fbshipit-source-id: d3f84dbfdea9e17c1e3919b4918e8f6c09cb6ade