Fix OSS build failure
Summary:
Recent refactoring changes [broke the build](https://github.com/facebookincubator/ktfmt/runs/4412662075?check_suite_focus=true):

```
Error:  Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.5.0:compile (compile) on project ktfmt: Compilation failure: Compilation failure:
Error:  /home/runner/work/ktfmt/ktfmt/core/src/main/java/com/facebook/ktfmt/testutil/KtfmtTruth.kt:[24,26] Unresolved reference: truth
```

This is because the `pom.xml` file limits the scope of of the test dependencies to the test scope. Moving `testutil` and `KtfmtTruth.kt` back to the `test` dir should fix the build.

Also, while touching the test BUCK file, clean up unneeded dependencies.

Differential Revision: D32874954

fbshipit-source-id: 4962f6cca72d764d4e60819a7ac57c766f1e44e0